package blog.anirbanm.inputlov.model.am;

import blog.anirbanm.inputlov.model.am.common.InputLOVModule;
import blog.anirbanm.inputlov.model.vo.TransientVOImpl;

import blog.anirbanm.inputlov.model.vo.TransientVORowImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 21 14:22:27 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InputLOVModuleImpl extends ApplicationModuleImpl implements InputLOVModule {
    /**
     * This is the default constructor (do not remove).
     */
    public InputLOVModuleImpl() {
    }
    
    public void initRow() {
        TransientVOImpl view = getTransientVO1();
        TransientVORowImpl row = (TransientVORowImpl) view.getCurrentRow();
        if (row != null) {
            row.remove();
        }
        row = (TransientVORowImpl) view.createRow();
        row.setKeyAttr(-1);
        view.insertRow(row);
    }
    
    public Boolean checkStatus() {
        Boolean status = true;
        TransientVOImpl view = getTransientVO1();
        TransientVORowImpl row = (TransientVORowImpl) view.getCurrentRow();
        if (row != null && row.getFirstNameAttr() != null) {
            RowSet rs = row.getEmployeesVA();
            System.out.println("Entering checkStatus for " + row.getFirstNameAttr());
            Row[] filteredRows = rs.getFilteredRows("FirstName", row.getFirstNameAttr());
            status = filteredRows.length > 0;
            row.setEmpExistsAttr(status);
        }
        System.out.println(printRow());
        System.out.println("Exiting checkStatus with " + status);
        return status;
    }
    
    public String printRow() {
        TransientVORowImpl row = (TransientVORowImpl) getTransientVO1().getCurrentRow();
        return row.toString();
    }

    /**
     * Container's getter for TransientVO1.
     * @return TransientVO1
     */
    public TransientVOImpl getTransientVO1() {
        return (TransientVOImpl) findViewObject("TransientVO1");
    }
}

