package blog.anirbanm.inputlov.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 21 14:23:29 IST 2018
// ---------------------------------------------------------------------
public interface InputLOVModule extends ApplicationModule {

    void initRow();

    String printRow();

    Boolean checkStatus();
}

