package blog.anirbanm.inputlov.model.vo;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 21 12:55:26 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransientVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        KeyAttr,
        FirstNameAttr,
        EmpStatusAttr,
        EmpExistsAttr,
        EmployeesVA;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int KEYATTR = AttributesEnum.KeyAttr.index();
    public static final int FIRSTNAMEATTR = AttributesEnum.FirstNameAttr.index();
    public static final int EMPSTATUSATTR = AttributesEnum.EmpStatusAttr.index();
    public static final int EMPEXISTSATTR = AttributesEnum.EmpExistsAttr.index();
    public static final int EMPLOYEESVA = AttributesEnum.EmployeesVA.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TransientVORowImpl() {
    }
    
    @Override
    public String toString() {
        return "TransientVORowImpl ["
            + getKeyAttr() + " "
            + getFirstNameAttr() + " "
            + getEmpStatusAttr() + "]";
    }

    /**
     * Gets the attribute value for the calculated attribute KeyAttr.
     * @return the KeyAttr
     */
    public Integer getKeyAttr() {
        return (Integer) getAttributeInternal(KEYATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KeyAttr.
     * @param value value to set the  KeyAttr
     */
    public void setKeyAttr(Integer value) {
        setAttributeInternal(KEYATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FirstNameAttr.
     * @return the FirstNameAttr
     */
    public String getFirstNameAttr() {
        return (String) getAttributeInternal(FIRSTNAMEATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FirstNameAttr.
     * @param value value to set the  FirstNameAttr
     */
    public void setFirstNameAttr(String value) {
        setAttributeInternal(FIRSTNAMEATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EmpStatusAttr.
     * @return the EmpStatusAttr
     */
    public String getEmpStatusAttr() {
        return getEmpExistsAttr() == null ? (String) getAttributeInternal(EMPSTATUSATTR) : 
            (getEmpExistsAttr() ? "Employee " + getFirstNameAttr() + " is on our list" 
            : "Employee " + getFirstNameAttr() + " is new");
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmpStatusAttr.
     * @param value value to set the  EmpStatusAttr
     */
    public void setEmpStatusAttr(String value) {
        setAttributeInternal(EMPSTATUSATTR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EmpExists.
     * @return the EmpExists
     */
    public Boolean getEmpExistsAttr() {
        return (Boolean) getAttributeInternal(EMPEXISTSATTR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmpExistsAttr.
     * @param value value to set the  EmpExistsAttr
     */
    public void setEmpExistsAttr(Boolean value) {
        setAttributeInternal(EMPEXISTSATTR, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EmployeesVA.
     */
    public RowSet getEmployeesVA() {
        return (RowSet) getAttributeInternal(EMPLOYEESVA);
    }
}

