package blog.anirbanm.inputlov.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 21 12:55:27 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransientVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TransientVOImpl() {
    }
}

